version: '3.7'

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/Documentos/volumes/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: consulta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata:
